// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaAxZ50YJrEIZBBfrIwR1V_apSsnToGTI',
    appId: '1:1080979433028:web:772dd68946caf1dfb4be11',
    messagingSenderId: '1080979433028',
    projectId: 'aloziraat-62060',
    authDomain: 'aloziraat-62060.firebaseapp.com',
    databaseURL: 'https://aloziraat-62060-default-rtdb.firebaseio.com',
    storageBucket: 'aloziraat-62060.appspot.com',
    measurementId: 'G-TDK42NJ0CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2SjqoIo4N8edC3jSp5C2AvGk88n8Gpio',
    appId: '1:1080979433028:android:01f2c7fce93cdc86b4be11',
    messagingSenderId: '1080979433028',
    projectId: 'aloziraat-62060',
    databaseURL: 'https://aloziraat-62060-default-rtdb.firebaseio.com',
    storageBucket: 'aloziraat-62060.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRzph3K_iH2fsPUsvL5rSAUY2EmaRxtMg',
    appId: '1:1080979433028:ios:384f877df9ccdf2ab4be11',
    messagingSenderId: '1080979433028',
    projectId: 'aloziraat-62060',
    databaseURL: 'https://aloziraat-62060-default-rtdb.firebaseio.com',
    storageBucket: 'aloziraat-62060.appspot.com',
    iosClientId: '1080979433028-ardi4hmqsd89rpr3khee4vr1d3cofm3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.kayitlar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRzph3K_iH2fsPUsvL5rSAUY2EmaRxtMg',
    appId: '1:1080979433028:ios:384f877df9ccdf2ab4be11',
    messagingSenderId: '1080979433028',
    projectId: 'aloziraat-62060',
    databaseURL: 'https://aloziraat-62060-default-rtdb.firebaseio.com',
    storageBucket: 'aloziraat-62060.appspot.com',
    iosClientId: '1080979433028-ardi4hmqsd89rpr3khee4vr1d3cofm3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.kayitlar',
  );
}
